### ISSUE TITLE
go.mod: fix module path

### ISSUE THREAD

**Issue by nikkicoon** [zombiezen/go-sqlite#111]
When I try to use this module instead of go-llsqlite, I get this:
```
go: github.com/zombiezen/go-sqlite@v1.4.0: parsing go.mod:
	module declares its path as: zombiezen.com/go/sqlite
	        but was required as: github.com/zombiezen/go-sqlite
```
I know that this eventually to be fixed in go with redirects, but today it is not usable for me without forking it.
Could you please adjust this?

**Comment by zombiezen** [comment]
The correct import path for this module is `zombiezen.com/go/sqlite`. See the README for install instructions.

**Comment by nikkicoon** [comment]
thanks! I missed that note
