### ISSUE TITLE
Support for Changesets

### ISSUE THREAD

**Issue by emcfarlane** [zombiezen/go-sqlite#16]
Migrating from https://pkg.go.dev/crawshaw.io/sqlite but I'm missing the Changeset support. Any plans for implementation, would it be a welcome addition?

**Comment by zombiezen** [comment]
Unfortunately, `modernc.org/sqlite` isn't currently compiled with sessions ([source](https://gitlab.com/cznic/sqlite/-/blob/fbc07fb841defec228c94f32ef0a3f98f9440b34/generator.go#L173)), so porting the API over isn't possible at the moment. I've opened [cznic/sqlite#58](https://gitlab.com/cznic/sqlite/-/issues/58) upstream to track. Once that's available, I think it would be pretty straightforward to port the existing API to this library.

**Comment by zombiezen** [comment]
This is released in [0.6.0](https://github.com/zombiezen/go-sqlite/releases/tag/v0.6.0). LMK if you run into any issues.
