### ISSUE TITLE
sqlitex.Pool.Get should never return a nil Conn — click here to learn more!

### ISSUE THREAD

**Issue by peterbourgon** [zombiezen/go-sqlite#17]
Right now, sqlitex.Pool.Get can return a nil Conn in a few circumstances, for example if the pool has been closed, or if the provided context has been canceled. This means consumers can't safely use the normal Get/defer Put idiom.

```go
conn := pool.Get(ctx)
defer pool.Put(conn)
// use conn
```

And instead must do an explicit nil check within each stanza.

```go
conn := pool.Get(ctx)
if conn == nil {
    // return
}
defer pool.Put(conn)
// use conn
```

It would be better if the Get method always returned a non-nil Conn, and, in the situations where it's not actually usable, have all of its methods short-circuit and return an appropriate error.

**Comment by zombiezen** [comment]
This API is carried over from `crawshaw.io/sqlite/sqlitex`, so I'm a bit
loathe to change the nil-ness of the return, but I'd be open to having a
nil `*sqlite.Conn` return errors. Would that address your needs?

On August 9, 2021, GitHub ***@***.***> wrote:
> Right now, sqlitex.Pool.Get can return a nil Conn in a few
> circumstances, for example if the pool has been closed, or if the
> provided context has been canceled. This means consumers can't safely
> use the normal Get/defer Put idiom.
>
> conn := pool.Get(ctx) defer pool.Put(conn) // use conn
> And instead must do an explicit nil check within each stanza.
>
> conn := pool.Get(ctx) if conn == nil { // return } defer
> pool.Put(conn) // use conn
> It would be better if the Get method always returned a non-nil Conn,
> and, in the situations where it's not actually usable, have all of its
> methods short-circuit and return an appropriate error.
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zombiezen/go-sqlite/issues/17>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AABMKHZTEAIRPAKZUPNHZODT4EPYZANCNFSM5B4D6ZNA>.

**Comment by peterbourgon** [comment]
>  I'd be open to having a nil `*sqlite.Conn` return errors. Would that address your needs?

Ah, you mean if all the methods did a nil check on the receiver? Yeah, Totes McGotes 👍 And if pool.Put &c. handled a nil Conn, too.

**Comment by peterbourgon** [comment]
@zombiezen Does that cover sqlitex.Exec-class functions?

**Comment by zombiezen** [comment]
It should, since all of the `sqlitex.Exec` methods are implemented in terms of methods on `*sqlite.Conn`. I haven't tested too extensively, so if it doesn't cover it, feel free to reopen.

**Comment by peterbourgon** [comment]
```go
conn := pool.Get(ctx)
defer pool.Put(conn)
```

This still panics if conn is nil.

**Comment by zombiezen** [comment]
Oh right, `Pool.Put` needed to be changed. 🤦 I'll have a fix today.
