### ISSUE TITLE
"Disable double-quoted string literals" broke my usage

### ISSUE THREAD

**Issue by peterbourgon** [zombiezen/go-sqlite#19]
Commit ed99db83671cdf65aeb34b1bcd490ba66d712e97 made it so the query

```
SELECT count() FROM objects WHERE id == "baz";
```

which previously returned 0, to error with

```
sqlutil.Exec: sqlite: prepare "SELECT count() FROM objects WHERE id == \"baz\"": SQL logic error: no such column: baz
```

Am I doing something wrong?

**Comment by peterbourgon** [comment]
Pretty sure it's a bug, as

```
SELECT count() FROM objects WHERE id == 'baz';
```

works as expected.

**Comment by zombiezen** [comment]
See https://www.sqlite.org/lang_keywords.html

Double quotes are used to escape column identifiers, but SQLite has a quirks mode where they can be used as a string delimiter if no such column exists for historical compatibility. `crawshaw.io/sqlite` had the default quirks mode off, which is what that commit is restoring.

**Comment by peterbourgon** [comment]
Huh! TIL!
