### ISSUE TITLE
sqlitemigration: Use table instead of pragma user_version

### ISSUE THREAD

**Issue by tv42** [zombiezen/go-sqlite#25]
I believe SQLite's `PRAGMA user_version` is one of those shiny traps. It looks like it'll do what you want for schema migrations, but **it's not included in a database dump**. Dump+restore will confuse your schema migration mechanism.

Instead, please consider using a table to store the schema version.

For inspiration: https://github.com/tv42/securityblanket/tree/master/internal/schema

**Comment by zombiezen** [comment]
Doesn't its inclusion in a database dump depend on the mechanism? I'm assuming you're referring to using the `.dump` command from the SQLite shell.

**Comment by tv42** [comment]
I mean `sqlite3 mydb.sqlite .dump`, yes. That is what I think most people will use. I am not aware of any commonly-in-use sqlite backup mechanism that would include `user_version`.

**Comment by zombiezen** [comment]
I appreciate the suggestion, but I have enough production code that relies on the current behavior that I'm not ready to change at this time. There's nothing stopping someone from developing/using a different migration mechanism/package with `zombiezen.com/go/sqlite`. `user_version` works with [Litestream](https://litestream.io/), which is the backup mechanism I use.

**Comment by tv42** [comment]
Maybe a mention in the docs to not use `sqlite3 foo.sqlite .dump`?
