### ISSUE TITLE
Transaction helpers don't work when manual BEGIN/END do

### ISSUE THREAD

**Issue by anacrolix** [zombiezen/go-sqlite#33]
Using sqlitex.Transaction I get a lot of:

    sqlite: step: database is locked: cannot commit transaction - SQL statements in progress

But if I manually sqlitex.Exec(... "BEGIN") and "END", I don't have this problem. Is there a difference I should be aware of?

**Comment by anacrolix** [comment]
This might be a subtle error in my own calling code. I get the same issue with crawshaw.

**Comment by zombiezen** [comment]
Seems that the error message indicates a statement that has not been stepped through fully: https://sqlite.org/forum/info/52f001ddd522c2bd

Can you post a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by anacrolix** [comment]
I think it has to do with unclosed incremental BLOB handles, which may be undocumented?

**Comment by zombiezen** [comment]
That's quite possible: blob handles are guaranteed to be a snapshot of their value during the transaction.

**Comment by anacrolix** [comment]
It looks like stmt_finalize is called from sqlite3_blob_close and that decrements a write counter that prevents savepoints. I don't think this is an issue in this implementation but a general sqlite issue. Thanks Ross
