### ISSUE TITLE
Expose valid int64 types

### ISSUE THREAD

**Issue by delaneyj** [zombiezen/go-sqlite#39]
Get/SetInt64 is great but per the [SQLite docs](https://www.sqlite.org/datatype3.html)...

> INTEGER. The value is a signed integer, stored in 0, 1, 2, 3, 4, 6, or 8 bytes depending on the magnitude of the value.

This would be we should be able to use 
```go
byte
int8
int16
int32
int64
uint8
uint16
uint32
uint64
```
By using the proper size we eliminate extra casting and memory allocations

**Comment by zombiezen** [comment]
I'm not sure what you're asking for here. The underlying C API doesn't expose anything beyond 64-bit signed integers (there are int versions for easy usage in C, but basically equivalent to what this wrapper does): https://www.sqlite.org/c3ref/column_blob.html

The doc you're citing describes the on-disk format, which is selected automatically based on the value itself. The casting may be an inconvenience, but IMO makes it explicit what is occurring, especially that uint64 isn't supported. AFAIK, there are no extra allocations, just sign extensions which are cheap.

**Comment by delaneyj** [comment]
Ah, my fault... I thought the C side **did** expose those, not just the on disk model.  Figured instead of casting unnecessarily it could just pass through.  Int64 to UInt64 is cheap.  Just didn't want int64->u8 casts when its wasn't needed.
