### ISSUE TITLE
ability to customize connection creatd by sqlitex.Pool

### ISSUE THREAD

**Issue by graf0** [zombiezen/go-sqlite#65]
Hi!

It would be greate to allow custom function to change connection params created by sqlitex.Pool
This way user can decide ie.: to set custom collator, or create module for virtual tables etc. - for each new connection created by pool.

**Comment by zombiezen** [comment]
This functionality exists in the [`sqlitemigration` package](https://pkg.go.dev/zombiezen.com/go/sqlite/sqlitemigration), but not in the `sqlitex.Pool` type. I agree that Pool should have this functionality, though. I can add that in the next few days.
