### ISSUE TITLE
provide table with missing/not supported features

### ISSUE THREAD

**Issue by vtolstov** [zombiezen/go-sqlite#7]
big thanks for such package, can you provide some table that have missing feature vs CGO sqlite package?

**Comment by zombiezen** [comment]
There isn't any feature gap AFAIK, since `modernc.org/sqlite/lib` (what this package uses under the hood) is an automatic translation of the SQLite C source into Go.

**Comment by vtolstov** [comment]
oh, surprising , i'm try to switch from sqlite3 to to native package =).
