### ISSUE TITLE
add example for database/sql usage

### ISSUE THREAD

**Issue by vtolstov** [zombiezen/go-sqlite#8]
maybe i'm miss something, but how can i use it with database/sql ?

**Comment by zombiezen** [comment]
If you're looking to use `database/sql`, you're going to want to use [`modernc.org/sqlite`](https://pkg.go.dev/modernc.org/sqlite) directly.

The reason for this package (and the original `crawshaw.io/sqlite` API) is to have tighter control over connections and use SQLite-specific features. David Crawshaw wrote a blog post describing why `database/sql` isn't a great fit for SQLite: https://crawshaw.io/blog/go-and-sqlite

Check out the [package examples](https://pkg.go.dev/zombiezen.com/go/sqlite#pkg-examples) if you want to get an idea of how to use this package. It's not a huge leap from `database/sql`, but allows you to perform [blob I/O](https://pkg.go.dev/zombiezen.com/go/sqlite#Blob) and [define your own functions](https://pkg.go.dev/zombiezen.com/go/sqlite#Conn.CreateFunction).
