### ISSUE TITLE
Extented error codes aren't reported properly

### ISSUE THREAD

**Issue by aureliar8** [zombiezen/go-sqlite#84]
# What I see 
I faced an issue were an error was returned while trying to open a corrupted database. 

`OpenConn` returned this error: `sqlite: open "path.db": disk I/O error: disk I/O error`

# What I would like
The `disk I/O error: disk I/O error` part could be improved to both remove the duplication and give a more precise error message. 

This part of the error is generated by `(*Conn).extreserr(res)`. 
After more investigation and adding debug logs in the library I realized that the error code passed to this function was `ResultIOErrShortRead`. 

It would be nice to add this constant `SQLITE_IOERR_SHORT_READ` in the error message. It can be generated simply via `(ResultCode).String()`

# How to change it 
This piece of code to generate a readable error from a ResultCode could be changed from 
```go
type sqliteError struct {
	code ResultCode
}

func (e sqliteError) Error() string {
	return e.code.Message()
}
```
to
```go
type sqliteError struct {
	code ResultCode
}

func (e sqliteError) Error() string {
	return e.code.String() + ": " +  e.code.Message()
}
```

I also think this piece of code could also be removed as it is the one that cause the duplicated error message:
```go
func (c *Conn) extreserr(res ResultCode) error {
	if res.IsSuccess() {
		return nil
	}
	if msg := libc.GoString(lib.Xsqlite3_errmsg(c.tls, c.conn)); msg != "" { // <- Remove this as the error message can alredy be generated from res.ToError()
		return fmt.Errorf("%w: %s", res.ToError(), msg)
	}
	return res.ToError()
}

```

If you agree with those changes I'd be happy to provide a PR

**Comment by zombiezen** [comment]
Thanks for the report. I've been thinking this over for the last week and I don't believe adding the SQLite constant name to every error message is in the best interest of most users. While it's unfortunate the extended error codes in this case do not provide a more useful message, I think that addressing that in upstream SQLite is better for the ecosystem, if you want to bring it up there. The responsibility and scope of this project is to be a pretty direct binding to SQLite but adapt it for Go idioms.

As you saw, applications that want to log more detailed information about failures can already use `sqlite.ErrCode` to extract the more exact failure and do custom reporting.

I did address the potential duplication issue by skipping the branch you mentioned if the message reported by the connection is the same as the result code's message. However, in tracing the code, opening a connection does not call `extreserr` at any point, which suggests this string is what SQLite returns, not what this library returns.
