### ISSUE TITLE
file:memory does not appear to work

### ISSUE THREAD

**Issue by dkotik** [zombiezen/go-sqlite#92]
Dear maintainer,

I use the sqlitex.Pool for simulating in-memory testing connections, but it does not appear to work when using `file:memory?mode=memory` with multiple connections as described below:

```go
func NewPool(uri string, opts PoolOptions) (pool *Pool, err error) {
	if uri == ":memory:" {
		return nil, strerror{msg: `sqlite: ":memory:" does not work with multiple connections, use "file::memory:?mode=memory"`}
	}
       // ...
}
```

- [x] Created tables are unique per connection instead of being shared in the Pool. Using PrepareConn option just creates individual tables in fragmented memory space - the data is not shared between connections.
- [x] There is a small typo there with double `::` between file and memory.

I care about this, because my authorization code occasionally may make a database call, which will block the Pool, making this impossible to test. I can work around this by writing my own wrapper around the Pool and returning the same connection when in `file:memory:" mode, but I want to know if I am doing something wrong here, or may be there is a better way. Thank you!

**Comment by zombiezen** [comment]
You will also need to pass in [`OpenSharedCache`](https://pkg.go.dev/zombiezen.com/go/sqlite#OpenSharedCache) (not on by default) in order for a pool of in-memory connections to work as you expect.

**Comment by dkotik** [comment]
> edit: I believe adding &cache=shared will also work. If that's the case, the error message should probably be amended to include that to avoid future confusion.

This worked perfectly! You are amazing!

**Comment by dkotik** [comment]
I will gladly submit a documentation PR - would you like me to? I write ok docs.

**Comment by zombiezen** [comment]
Sure, sounds good. 👍
