### ISSUE TITLE
Stmt.findBindName shoud be public

### ISSUE THREAD

**Issue by shaunco** [zombiezen/go-sqlite#95]
`Stmt.ColumnIndex` is public, but `Stmt.findBindName` is private. When writing generic helper functions, like one that serializes a protobuf object to/from a BLOB column/field, it is nice to be able to mimic the `Set/Bind` and `Get/Column` pattern that `Stmt` already uses, but it is currently not possible on the `Set` functions without duplicating all the code in my `Bind` since there isn't a public `findBindName` I can call.

**Comment by shaunco** [comment]
Sure, I can reimplement the `findBindName` code on my own, but it seemed more forward compatible to just expose the function in case you decide to optimize it to a map lookup or something else in the future.

**Comment by zombiezen** [comment]
Understood. If the implementation changes dramatically, I'll keep that in mind. For now, I'm going to close this because the public API as it exists now seems sufficient.
